import { describe, it } from 'node:test';
import * as assert from 'node:assert';
import { canonicalizeIntentProof } from '../src/canon';

// Fixture: pre-generated Go tools/pkg/canon output for a sample policy body.
// Generated by Go canonicalizer on 2026-05-13.
const goCanonicalOutput =
  '{"policy_id":"tnt.test","policy_version":1,"rules":[{"category":"required","id":"r1","severity":"high","spec":{"action":"a"}}],"schema":"intentproof.policy.v1","scope":{"any_event_action_in":["a"]},"spec_version":"1.0.0","tenant_id":"tnt"}';

describe('canon cross-check against Go tools/pkg/canon', () => {
  it('produces byte-identical output for a sample policy body', () => {
    const body = {
      schema: 'intentproof.policy.v1',
      policy_id: 'tnt.test',
      policy_version: 1,
      tenant_id: 'tnt',
      spec_version: '1.0.0',
      scope: { any_event_action_in: ['a'] },
      rules: [
        {
          id: 'r1',
          category: 'required',
          severity: 'high',
          spec: { action: 'a' },
        },
      ],
    };

    const got = canonicalizeIntentProof(body);
    assert.strictEqual(
      got,
      goCanonicalOutput,
      'Node canonicalizer must match Go tools/pkg/canon byte-for-byte'
    );
  });
});
